### ISSUE TITLE
The closing brackets cause wrong path 

### ISSUE THREAD

**Issue by franpog859** [exlskills/course-golang-scalable-webservices-intro#1]
## Description
If there is an ending in a path like `.../something/` and after it there is a closing bracket browser involves it in the path causing wrong path like `https://docs.docker.com/compose/install/)`.
[Here](https://github.com/exlskills/course-ASAP-golang-scalable-webservices/blob/master/00_Introduction/00_Overview/00_Intro/index.md) is the file I'm talking about.
Problem exists on exlskills.com portal. I can't reproduce it in the `index.md` file.
It occured on Chrome 70.0.3538.102

## Image:
![image](https://user-images.githubusercontent.com/32485355/48918850-8ee66d00-ee8f-11e8-9540-dad0580d6a0b.png)

## Suggestion
It should direct with the correct path. I suggest to use links as I did [here](https://exlskills.com/learn-en/dashboard) (see the raw issue).

**Comment by svarlamov** [comment]
@franpog859 Thank you for tracking this down and contributing such a detailed issue report -- it's much appreciated! I have updated that MD file to address the issue and will also keep this in mind when building future courses!
